### ISSUE TITLE
Unsure of how compilation is supposed to work - "textcat" tutorial

### ISSUE THREAD

**Issue by vineetparikh** [TeamCohen/ProPPR#13]
I'm not able to figure out why I'm getting this error when going through the textcat tutorial:
```Error: Could not find or load main class edu.cmu.ml.proppr.QueryAnswerer INFO:root:call failed (status 1): java -cp .:/home/vince/pgx-demo-app/ref/ProPPR/conf/:/home/vince/pgx-demo-app/ref/ProPPR/bin:/home/vince/pgx-demo-app/ref/ProPPR/lib/* edu.cmu.ml.proppr.QueryAnswerer --queries toytrain.examples --solutions toytrain.solutions.txt --programFiles textcat.wam:toylabels.cfacts:toycorpus.graph```

I made sure to go through the whole tutorial, up to the point where I'm running
```proppr answer toytrain.examples```

What does this error mean, and how could I fix this?

**Comment by krivard** [comment]
Can you paste the output of the following:

    $ git branch
    [...]
    $ ant clean build
    [...]
    $ find bin -name "*.class" | head

**Comment by vineetparikh** [comment]
```
$ git branch
* working
$ ant clean build
Buildfile: /home/vince/pgx-demo-app/ref/ProPPR/build.xml

clean:

build-subprojects:

init:
    [mkdir] Created dir: /home/vince/pgx-demo-app/ref/ProPPR/bin

build-project:
     [echo] ProPPR: /home/vince/pgx-demo-app/ref/ProPPR/build.xml
    [javac] Compiling 123 source files to /home/vince/pgx-demo-app/ref/ProPPR/bin
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
     [copy] Copying 2 files to /home/vince/pgx-demo-app/ref/ProPPR/bin

build:

BUILD SUCCESSFUL
Total time: 3 seconds
$ find bin -name "*.class" | head
bin/edu/cmu/ml/proppr/Trainer$Parse.class
bin/edu/cmu/ml/proppr/util/ModuleConfiguration$SRWS.class
bin/edu/cmu/ml/proppr/util/ConcurrentSymbolTable.class
bin/edu/cmu/ml/proppr/util/ConcurrentSymbolTable$HashingStrategy.class
bin/edu/cmu/ml/proppr/util/ModuleConfiguration.class
bin/edu/cmu/ml/proppr/util/ParamsFile.class
bin/edu/cmu/ml/proppr/util/SymbolTable.class
bin/edu/cmu/ml/proppr/util/ModuleConfiguration$REGULARIZERSCHEDULES.class
bin/edu/cmu/ml/proppr/util/ModuleConfiguration$LOSSFUNCTIONS.class
bin/edu/cmu/ml/proppr/util/TimestampedWeight.class

**Comment by vineetparikh** [comment]
It looks like rebuilding seems to have worked: I was able to finish the tutorial! Thank you so much for your help!
